// `.env.ts` is generated by the `npm run env` command
//import env from './.env';

export const environment = {
  production: false,
  version: 1,
  serverUrl: 'http://18.215.170.41:7000/api/',
  LiveUrl: 'http://10.1.151.122:8000/api/',
  ReportPath: 'http://10.1.151.122/report/',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR']
};
